version: 0.0
os: linux

files:
  - source: docker-compose.prod.yml
    destination: /home/ubuntu/app
  - source: .env.images
    destination: /home/ubuntu/app
  - source: scripts/
    destination: /home/ubuntu/app/scripts

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 10000
      runas: ubuntu
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 10000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 10000
      runas: ubuntu
  
  #ValidateService:
  #  - location: scripts/validate_service.sh
  #    timeout: 10000
  #    runas: ubuntu