services:
  api:
    build: ./api
    container_name: api-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    depends_on:
      - db

  mqtt:
    build: ./mqtt
    container_name: mqtt-service
    ports:
      - "1883:1883"
    env_file:
      - .env
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
